# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: [ README.md, LICENSE, staticman.yml] # files to exclude
include: [ .well-known ]
plugins: [ jekyll-paginate ]
highlighter: rouge
markdown: kramdown
url: https://www.christiansaga.de
title: christiansaga.de
description: Personal website
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: christiansaga.de

author:
  name: Christian Saga
  email:
  github:
  twitter:
  mastodon:
  linkedin:
  bio: Personal website

# Make sure you create the following in /pages when set
rss_path: /feed.xml
categories_path: /categories.html
tags_path: /tags.html
about_path: /about.html
#contact_path: /contact.html

BASE_PATH:
